services:
  middleware:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - SERVER1_IP=${SERVER1_IP}
      - SERVER2_IP=${SERVER2_IP}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
