services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:4000"
    environment:
      - INSTANCE_ID=${INSTANCE_ID}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - middelware_app-network # Cambia el nombre de la red para que coincida

networks:
  middelware_app-network:
    # Asegúrate de que la red coincida con la del otro archivo
    external: true
